Dataloader:
  train_batch_size: 8
  val_batch_size: 4
  test_batch_size: 4
Transform:
  train_random_crop_size: [320, 320]
Model:
  encoder: timm-efficientnet-b5
  siamese_head_kernel_size: 7
Scheduler:
  multistep_milestones: [60]
General:
  epochs: 120
  enable_swa: true
  swa_lr: 1e-4
  swa_epoch_start: 90