Data:
  train_dir: /data/train
  test_dir: /data/test
  artifact_dir: /wdata
  fold_ver: folds_v3
  pre_image_blacklist: [
    # Louisiana-East_Training_Public
    10300100AF395C00_2_18_35.tif,  # building FN
    10300100AF395C00_2_19_35.tif,  # building FN
    10400100684A4B00_1_22_70.tif,  # building FN
    10400100684A4B00_1_23_70.tif,  # building FN
    10400100684A4B00_1_24_70.tif,  # building FN
    10400100684A4B00_1_25_70.tif,  # building FN
    10400100684A4B00_1_26_70.tif,  # building FN
    #10400100684A4B00_1_2_84.tif,  # building FN
  ]
  use_mosaic_for_train: True
Dataloader:
  train_batch_size: 10
  train_num_workers: 6
  val_batch_size: 8
  val_num_workers: 6
  test_batch_size: 8
  test_num_workers: 6
Transform:
  train_random_crop_size: [512, 512]
  train_random_flip_prob: 0.0  # both of horizontal and vertical flip
  train_random_horizontal_flip_prob: 0.0
  train_random_vertical_flip_prob: 0.0
  train_random_rotate90_prob: 0.0
Model:
  type: seg
  arch: unet
  encoder: timm-efficientnet-b3
  n_input_post_images: 0
  n_siamese_head_convs: 2
  siamese_head_kernel_size: 3  # valid when n_siamese_head_convs>=2
  siamese_head_kernel_size_last: 1
  siamese_head_dilation_last: 1
  siamese_head_module: 'conv'  # valid when n_siamese_head_convs>=2. 'conv', 'conv_relu', or 'conv_bn_relu'
  enable_siamese_post_head: false
  post_head_kernel_size: 3  # valid when enable_siamese_post_head = true
  post_head_module: 'conv'  # valid when enable_siamese_post_head = true
  n_post_head_modules: 1  # valid when enable_siamese_post_head = true
  train_post_select_method: less_mse_prob  # valid when n_input_post_images=1 [always_post1, less_mse, or less_mse_prob] 
  test_post_select_method: less_mse  # valid when n_input_post_images=1 [always_post1 or less_mse]
Class:
  groups: [building, road]
  classes:
    building: [building, building_border, building_contact]
    road: [road, road_junction]
  class_weights:
    building: [1.0, 1.0, 1.0]
    road: [1.0, 1.0]
  losses:
    building: [dice, bce]
    road: [dice, bce]
  loss_weights:
    building: [1.0, 1.0]
    road: [1.0, 1.0]
Optimizer:
  type: adam
  lr: 2e-4
  weight_decay: 0
Scheduler:
  type: multistep
  multistep_milestones: [80]
  multistep_gamma: 0.1
  annealing_t_max: 120
  annealing_eta_min: 0.0
General:
  gpus: [0]
  epochs: 120
  fp16: true
  amp_backend: native # valid when fp16=true
  amp_level: null # valid when amp_backend=apex
  seed: 777
  deterministic: true
  benchmark: false
  check_val_every_n_epoch: 1
  val_metric_to_monitor: val/iou
  enable_ema: false
  ema_momentum: 2e-3  # valid when enable_ema=true
  enable_swa: false
  swa_lr: 2e-4  # valid when enable_swa=true
  swa_epoch_start: 90  # valid when enable_swa=true
